name: avec_moi_with_us
description: A movie and tv show recommendation app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  provider: ^6.0.0
  stroke_text: any
  flutter_bloc: ^8.1.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  liquid_pull_to_refresh: ^3.0.1
  toastification: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.6


flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - assets/icons/icon_rounded.png
  fonts:
    - family: McLaren
      fonts:
        - asset: assets/fonts/McLaren/McLaren-Regular.ttf
    - family: Kavoon
      fonts:
        - asset: assets/fonts/Kavoon/Kavoon-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  icon_size: 256
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#9680B4"
  image: assets/icons/icon_rounded.png
  branding: assets/icons/icon_rounded.png
  color_dark: "#9680B4"
  image_dark: assets/icons/icon_rounded.png
  branding_dark: assets/icons/icon_rounded.png

  android_12:
    image: assets/icons/icon_rounded.png
    icon_background_color: "#9680B4"
    image_dark: assets/icons/icon_rounded.png
    icon_background_color_dark: "#9680B4"

  web: false
