name: avec_moi_with_us
description: A movie and tv show recommendation app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  provider: ^6.0.0
  stroke_text: any
  flutter_bloc: ^8.1.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: McLaren
      fonts:
        - asset: assets/fonts/McLaren/McLaren-Regular.ttf
    - family: Kavoon
      fonts:
        - asset: assets/fonts/Kavoon/Kavoon-Regular.ttf